### PR TITLE
Feature/574 support agent invitation activities should be tracked with an audit table

### PR DESCRIPTION
**Pull request by despo**
## Trello card URL:
https://trello.com/c/NgLHcZvB/574-support-agent-invitation-activities-should-be-tracked-with-an-audit-table

## Changes in this PR:
- Adds PublicActivity
- Sets user + school models to trackable so that activities are created on every CRUD action
- Adds custom activities for 
  - associating a user to a school
  - inviting a user to a school
  - failed attempt to invite user to school

### CODE REVIEW

**Comment by despo** [comment]
[Support agent invitation activities should be tracked with an audit table](https://trello.com/c/NgLHcZvB/574-support-agent-invitation-activities-should-be-tracked-with-an-audit-table)

**Comment by lozette** [comment]
Are we bothered about how things look when there's no data in the staff/audit tables?

screenshot 2018-11-29 at 14 39 53

Also I'm a bit confused about the difference between "added to a school" and "invited to a school" - with the support agents know the difference? Is it more obvious to them?

**Comment by despo** [comment]
@lozette I tried moving the button around a bit, but It looked worse, so I thougt it might just be best to request for some of @gazaston's time in order to improve the UI once once we get our first production release out.

**Comment by lozette** [comment]
Happy with this 🚀

**Pull request merged**
